env: local
host: http://localhost:8080

server.port: 8001

saro.rdb:
  driverClassName: org.h2.Driver
  jdbcUrl: "jdbc:h2:file:./anissia-local;AUTO_SERVER=TRUE"
  username: sa
  password: anissia

mail:
  enable: false
  path.conf: ./email.conf

server-forward-headers: true

spring.jpa:
  properties.hibernate:
#    format_sql: true
#    use_sql_comments: false
    jdbc.batch_size: 4
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: update

decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j
  log-format: "%(category) | %(executionTime)ms | %(sql)"

spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

