env: dev
host: http://localhost:8080

server.port: 8001

saro.rdb:
  driverClassName: org.mariadb.jdbc.Driver
  jdbcUrl: jdbc:mariadb://10.0.0.11:3306/anissia
  username: anissia
  password: anissia

mail:
  enable: false
  path.conf: ./email.conf

server-forward-headers: true

decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j
  log-format: "%(category) | %(executionTime)ms | %(sql)"

spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties.hibernate:
      jdbc.batch_size: 4
      dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

